# Generated by Django 4.2.2 on 2023-06-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="diploma",
            field=models.ImageField(null=True, upload_to="diploma/"),
        ),
    ]
